#!/usr/bin/env python3

# ToBeGreen is a python3 library used for (de)serialization between python data objects and blobs.
# Copyright (C) 2020 Stephen Fedele <32551324+strangeprogrammer@users.noreply.github.com>
# 
# This file is part of ToBeGreen.
# 
# ToBeGreen is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ToBeGreen is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# and the GNU Lesser General Public License along with ToBeGreen.  If not, see
# <https://www.gnu.org/licenses/>.
# 
# Additional terms apply to this file.  Read the file 'LICENSE.txt' for
# more information.



### Imports

import os
import setuptools
from setuptools import Extension, Command, find_packages
from setuptools.command.build_ext import build_ext
from setuptools.command.build_py import build_py
from distutils.command.clean import clean

### Global Variables

projroot = os.path.dirname(__file__) + "/"
src = projroot + "ToBeGreen/"

### Build Management

### Useful Commands

class clean_wrap(clean):
	"""Cleanup miscellaneous files generated by this script."""
	
	def run(self):
		print("removing dist-ish files")
		os.system("rm -rf " + projroot + "dist/")
		os.system("rm -rf " + projroot + "ToBeGreen.egg-info/")
		super().run()

### Setup

with open(projroot + "README.md", "r") as README:
	setuptools.setup(
		name = "ToBeGreen",
		version = "0.9.1",
		author = "strangeprogrammer",
		author_email = "32551324+strangeprogrammer@users.noreply.github.com",
		description = "ToBeGreen is a python3 library used for (de)serialization between python data objects and blobs.",
		long_description = README.read(),
		long_description_content_type = "text/markdown",
		url = "https://www.github.com/strangeprogrammer/ToBeGreen",
		cmdclass = {
			"clean": clean_wrap,
		},
		packages = ["ToBeGreen"],
		package_dir = {"": projroot},
		python_requires = ">=3.0",
	)
