#!/bin/bash

set -e

YELLOW=$(echo -e "\e[33m")
CYAN=$(echo -e "\e[36m")
NOCOLOR=$(echo -e "\e[39m")

cat << EOF
${YELLOW}Fix up the ${CYAN}release${YELLOW} and ${CYAN}version${YELLOW} number in ${CYAN}./docs/conf.py${YELLOW}, ${CYAN}./setup.py${YELLOW}, and ${CYAN}git tag${YELLOW} if a new version's out.${NOCOLOR}
EOF
